accounts/urls.py
from django.urls import path
from accounts.views import registration_view, \
    logout_view, \
    login_view, \
    account_view, \
    getAuthor, \
    change_password,\
    post_create,\
    PostUpdate

from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('profile/', account_view, name='profile'),
    path('author-profile/<username>', getAuthor, name='author'),
    # Authentication and Authorization
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('change-password/',change_password, name='change_password'),
    path('post_create/', post_create, name='post_create'),
    path('post_update/<int:id>', PostUpdate, name='post_update'),
    # Accounts utils
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # path('password_change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
    #      name='password_change_done'),
    #
    # path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
    #      name='password_change'),
    #
    # path('password_reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
    #      name='password_reset_done'),
    #
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #     template_name='registration/password_reset_confermation.html'
    # ),
    #      name='password_reset_confirm'),
    #
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
    #      name='password_reset'),
    #
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    #      name='password_reset_complete'),

    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('single_article/<int:id>/',views.single_article, name='single_article'),
    path('category/<slug:slug>/<int:id>/',views.article_category, name='article_category'),
    path('search_posts/', views.search_posts, name='search_posts'),
    path('show_video/',views.show_video, name='show_video'),
    path('about-us/',views.about_us, name='about_us'),
    path('contact-us/',views.contact_us, name='contact_us'),




]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls')),
    path('newsletters/', include('newsletters.urls', namespace='newsletters')),
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls','jet-dashboard')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),



]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

from phonenumber_field import modelfields


class AccountsManager(BaseUserManager):
    def create_user(self, email, username, password=None):  # fields which are used when creating accounts
        if not email:
            raise ValueError("User must have an Email address")
        if not username:
            raise ValueError("User must have an Username ")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True

        user.save(using=self._db)
        return user


class Accounts(AbstractBaseUser):
    name = models.CharField(max_length=50, verbose_name="Full Name", null=True)
    email = models.EmailField(verbose_name="email", max_length=255, unique=True)
    username = models.CharField(max_length=50, unique=True)
    # add user own fields to model account
    dob = models.DateField(verbose_name="Date of Birth", null=True)
    address = models.CharField(max_length=1024, verbose_name="Address", null=True)
    bio = models.CharField(max_length=1000, verbose_name="About", null=True)
    phone_number = modelfields.PhoneNumberField(blank=True)

    # ------------------ #
    image = models.ImageField(default='profile_image.png', upload_to='profile_pics')
    # ------------------ #
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    # ----------------------------------------------------#
    USERNAME_FIELD = 'email'  # field name which user should identifies Ex: email/username
    REQUIRED_FIELDS = ['username', ]  # field name which must be fill for creating accounts Ex: name, mobile, etc

    objects = AccountsManager()

    def __str__(self):
        return self.email  # data which should print when object of accounts class is printing

    def has_perm(self, perm, obj=None):
        return self.is_admin  # return true if user has permission to access Ex: it returns true if user is admin

    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from accounts.models import Accounts
from blog.models import Post

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=255, help_text='Required a valid email address')

    # TODO: form editing

    class Meta:
        model = Accounts
        fields = ('name','email', 'username', 'password1', 'password2')


class AccountAuthenticateForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Accounts
        fields = ('email', 'password')

    def clean(self):
        try:
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid email or password.")
        except KeyError:
            raise forms.ValidationError('Invalid credentials')


class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Accounts
        fields = ('email', 'username', 'name', 'dob', 'address', 'bio', 'phone_number', 'image')

    def clean_email(self):
        if self.is_valid():
            try:
                email = self.cleaned_data['email']
                account = Accounts.objects.exclude(pk=self.instance.pk).get(email=email)
            except KeyError:
                raise forms.ValidationError('Invalid Email')
            except Accounts.DoesNotExist:
                return email
            raise forms.ValidationError('Email "%s" is already in use.' % email)

    def clean_username(self):
        if self.is_valid():
            try:
                username = self.cleaned_data['username']
                account = Accounts.objects.exclude(pk=self.instance.pk).get(username=username)
            except KeyError:
                raise forms.ValidationError('Invalid Username')
            except Accounts.DoesNotExist:
                return username
            raise forms.ValidationError('Username: "%s" is not available to use.' % username)


class CreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [
            'title',
            'slug',
            'body',
            'image',
            'category',
            'tags',
        ]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.contrib.auth.decorators import login_required
from accounts.forms import RegistrationForm, AccountAuthenticateForm, AccountUpdateForm, CreateForm
from blog.models import Category
from .models import Accounts
from blog.models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#For password change import
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.conf import settings

# Create your views here.
def registration_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()  # Save User data
            # login user with newly register data
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('accounts:profile')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'accounts/register.html', context)


def login_view(request):
    context = {}
    if request.user.is_authenticated:
        return redirect('blog:index')
    if request.method == 'POST':
        form = AccountAuthenticateForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(request, username=email, password=password)
            print(user)
            if user is not None:
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get("next"))
                else:
                    return redirect('blog:index')
        else:
            context['login_form'] = form
    else:
        form = AccountAuthenticateForm()
        context['login_form'] = form
    return render(request, "accounts/login.html", context)


def logout_view(request):
    logout(request)
    return redirect('blog:index')


@login_required()
def account_view(request):
    context = {}
    if request.POST:
        form = AccountUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            context['success_message'] = 'Data Updated'
    else:
        form = AccountUpdateForm(initial={
            'email': request.user.email,
            'username': request.user.username,
            'image': request.user.image.url,
            'name': request.user.name,
            'dob': request.user.dob,
            'address': request.user.address,
            'bio': request.user.bio,
            'phone_number': request.user.phone_number,
        }
        )
    context['account_form'] = form
    return render(request, 'accounts/profile.html', context)

@login_required
def post_create(request):
    if request.user.is_authenticated:
        u = get_object_or_404(Accounts, email=request.user.email)
        form = CreateForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = u
            instance.save()
            return redirect('blog:index')
        return render(request, 'accounts/post_create.html', {"form": form,})
    else:
        return redirect('blog:index')

@login_required
def PostUpdate(request, id):
    if request.user.is_authenticated:
        u = get_object_or_404(Accounts, email=request.user.email)
        post = get_object_or_404(Post, id=id)
        form = CreateForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = u
            instance.save()
            messages.success(request, "Post updated successfully")
            return redirect('accounts:author', username=u.username)
        return render(request, 'accounts/post_create.html', {"form": form,})
    else:
        return redirect('accounts:login')

@login_required()
def getAuthor(request, username):
    user = get_object_or_404(Accounts, username=username)
    posts = Post.objects.filter(author=user)
    small_posts = Post.objects.filter(author=user)[4:10]
    most_popular = Post.published_objects.all().order_by('-views')[:4]  # query for 4 most viewed post
    paginator = Paginator(posts, 4)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 4 if index >= 4 else 0
    end_index = index + 4 if index <= max_index else max_index
    page_range = paginator.page_range[start_index:end_index]
    context = {
        'posts':posts,
        'author': user,
        'items': items,
        'page_range': page_range,
        'small_posts': small_posts,
        'most_popular': most_popular,
    }
    return render(request,'accounts/author_profile.html', context)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('blog:index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form,
    })

templates/accounts/author_profile.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}
    {{ request.user.username }} posts
{% endblock %}

{% block content %}
<!-- ##### Blog Area Start ##### -->
<div class="blog-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-8">
                <div class="blog-posts-area">
                    {% for user_post in items %}
                    <!-- Single Featured Post -->
                    <div class="single-blog-post featured-post mb-30">
                        <div class="post-thumb">
                            <a href="{{ user_post.get_absolute_url }}"><img src="{{ user_post.image.url }}" alt=""></a>
                        </div>
                        <div class="post-data">
                            <a href="/category/{{ user_post.category.slug }}/{{ user_post.category.id }}/" class="post-catagory">{{ user_post.category.name }}</a>
                            <a href="{{ user_post.get_absolute_url }}" class="post-title">
                                <h6>{{ user_post.title }}</h6>
                            </a>
                            <div class="post-meta">
                                <p class="post-author"><a href="{% url 'accounts:post_update' id=user_post.id %}">Update</a></p>
                                <p class="post-excerp">{{user_post.body|truncatewords:40|safe}}</p>
                                <!-- Post Like & Post Comment -->
                                <div class="d-flex align-items-center">
                                    <a href="#" class="post-like"><img src="{% static 'img/core-img/like.png' %}" alt=""> <span>392</span></a>
                                    <a href="#" class="post-comment"><img src="{% static 'img/core-img/chat.png' %}" alt=""> <span>10</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h6>Hi {{ request.user.username }} you have no post! </h6>
                    <p>You can make a post.<a href="{% url 'accounts:post_create' %}">Click here</a></p>
                    {% endfor %}
                    <!-- ##### Pagination start ##### -->
                    {% if items.has_other_pages %}
                    <nav aria-label="Page navigation example" style="margin-top:-30px;">
                        <ul class="pagination mt-50">
                            {% if items.has_previous %}
                            <li class="page-item active">
                              <a class="page-link" href="?page={{ items.previous_page_number }}">Prev</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                              <a class="page-link"><span>Prev</span></a>
                            </li>
                            {% endif %}
                            {% for i in page_range %}
                                {% if items.number == i %}
                                  <li class="page-item active">
                                    <a class="page-link" href="#">{{i}}<span class="sr-only">(current)</span></a>
                                  </li>
                              {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                              {% endif %}
                            {% endfor %}
                            {% if items.has_next %}
                                <li class="page-item"><a class="page-link" aria-label="Next" href="?page={{items.next_page_number}}">Next</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link"><span>Next</span></a></li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                     <!-- ##### Pagination end ##### -->
                </div>
            </div>

            <div class="col-12 col-lg-4">
                <div class="blog-sidebar-area">

                    <!-- Latest Posts Widget -->
                    <div class="latest-posts-widget mb-50">
                        {% for sidepost in small_posts %}
                        <!-- Single Featured Post -->
                        <div class="single-blog-post small-featured-post d-flex">
                            <div class="post-thumb">
                                <a href="{{ sidepost.get_absolute_url }}"><img src="{{sidepost.image.url}}" alt=""></a>
                            </div>
                            <div class="post-data">
                                <a href="{% url 'blog:article_category' id=sidepost.id slug=sidepost.category.slug %}" class="post-catagory">{{ sidepost.category.name }}</a>
                                <div class="post-meta">
                                    <a href="{{ sidepost.get_absolute_url }}" class="post-title">
                                        <h6>{{sidepost.title}}</h6>
                                    </a>
                                    <p class="post-date"><span>{{ sidepost.posted|date:'H:i A' }}</span> | <span>{{ sidepost.posted|date:'F y' }}</span></p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>

                    <!-- Popular News Widget -->
                    <div class="popular-news-widget mb-30">
                        <h3>4 Most Popular News</h3>
                        {% for popular in most_popular %}
                        <!-- Single Popular Blog -->
                        <div class="single-popular-post">
                            <a href="{{ popular.get_absolute_url }}">
                                <h6><span>{{ forloop.counter }}</span>{{ popular.title }}</h6>
                            </a>
                            <p>{{ popular.posted|date:'F d, Y' }}</p>
                        </div>
                        {% empty %}
                        <h6>No post available </h6>
                        {% endfor %}
                    </div>

                    <!-- Newsletter Widget -->
                    <div class="newsletter-widget mb-50">
                        <h4>Newsletter</h4>
                        <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                        <form action="#" method="post">
                            <input type="text" name="text" placeholder="Name">
                            <input type="email" name="email" placeholder="Email">
                            <button type="submit" class="btn w-100">Subscribe</button>
                        </form>
                    </div>

                    <!-- Latest Comments Widget -->
                    <div class="latest-comments-widget">
                        <h3>Latest Comments</h3>

                        <!-- Single Comments -->
                        <div class="single-comments d-flex">
                            <div class="comments-thumbnail mr-15">
                                <img src="{% static 'img/bg-img/29.jpg' %}" alt="">
                            </div>
                            <div class="comments-text">
                                <a href="#">Jamie Smith <span>on</span> Facebook is offering facial recognition...</a>
                                <p>06:34 am, April 14, 2018</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Blog Area End ##### -->
{% endblock %}

templates/accounts/change_password.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Password Change {% endblock %}




{% block content %}


<div class="container" style="margin-top: -100px;">
    <h1 style="margin-top: 100px;" class="text-info">Change your Password? </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-lg btn-primary" type="Submit" value="Submit" style="margin-bottom: 20px;">
    </form>
</div>


{% endblock %}

templates/accounts/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}
    login
{% endblock %}

{% block content %}
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex align-items-center justify-content-center h-100">
      <div class="col-md-8 col-lg-7 col-xl-6">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
          class="img-fluid" alt="Phone image">
      </div>
      <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
        <span class="login100-form-title p-b-32">
            Account Login
        </span>
        <form method="POST">
          {% csrf_token %}
          {% if request.GET.next %}
              <input type="hidden" name="next" value="{{ request.GET.next }}">
          {% endif %}

          {% if login_form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                  {{ login_form.non_field_errors.as_text }}
              </div>
          {% endif %}
          <!-- Email input -->
          <div class="form-outline mb-4">
            <input id="email" name="email" type="text" value="" class="form-control form-control-lg" />
            <label class="form-label" for="email">Email address</label>
          </div>
          {% if login_form.email.help_text %}
              <small>{{ login_form.email.help_text }}</small>
          {% endif %}
          {% if login_form.email.errors %}
              <div class="alert alert-danger" role="alert">
                  {{ login_form.email.errors.as_text }}
              </div>
          {% endif %}
          <!-- Password input -->
          <div class="form-outline mb-4">
            <input id="password" name="password" type="password" class="form-control form-control-lg" />
            <label class="form-label" for="password">Password</label>
          </div>
          {% if login_form.password.help_text %}
              <small>{{ login_form.password.help_text }}</small>
          {% endif %}
          {% if login_form.password.errors %}
              <div class="alert alert-danger" role="alert">
                  {{ login_form.password.errors.as_text }}
              </div>
          {% endif %}
          <div class="d-flex justify-content-around align-items-center mb-4">
            <!-- Checkbox -->
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="form1Example3" checked />
              <label class="form-check-label" for="form1Example3"> Remember me </label>
            </div>
            <a href="{% url 'accounts:change_password' %}">Forgot password?</a>
          </div>

          <!-- Submit button -->
          <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>

          <div class="divider d-flex align-items-center my-4">
            <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
          </div>

          <a class="btn btn-primary btn-lg btn-block" style="background-color: #3b5998" href="#!"
            role="button">
            <i class="fab fa-facebook-f me-2"></i>Continue with Facebook
          </a>
          <a class="btn btn-primary btn-lg btn-block" style="background-color: #55acee" href="#!"
            role="button">
            <i class="fab fa-twitter me-2"></i>Continue with Twitter
          </a>
        </form>
      </div>
    </div>
  </div>
</section>
<style>
	.divider:after,
	.divider:before {
	content: "";
	flex: 1;
	height: 1px;
	background: #eee;
	}
	.login100-form-title {
      font-family: Raleway-Medium;
      font-size: 30px;
      color: #555555;
      line-height: 1.2;
      text-transform: uppercase;
      text-align: center;

      width: 100%;
      display: block;
    }

</style>
{% endblock %}

templates/accounts/post_create.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Create Post here {% endblock %}



{% block content %}
<div class="container">
    <div class="row">
        <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <button class="btn btn-success">Create Post</button>
        </form>
    </div>
</div>
{% endblock %}