blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('single_article/<int:id>/',views.single_article, name='single_article'),
    path('category/<slug:slug>/<int:id>/',views.article_category, name='article_category'),
    path('search_posts/', views.search_posts, name='search_posts'),
    path('show_video/',views.show_video, name='show_video'),
    path('about-us/',views.about_us, name='about_us'),
    path('contact-us/',views.contact_us, name='contact_us'),




]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls')),
    path('newsletters/', include('newsletters.urls', namespace='newsletters')),
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls','jet-dashboard')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),



]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletters/urls.py
from django.urls import path

from . import views

app_name = 'newsletters'

urlpatterns = [
    path('subscribe/', views.newsletter_subscribe, name='subscribe'),
    path('unsubscribe/',views.newsletter_unsubscribe, name='unsubscribe'),

]

newsletters/models.py
from django.db import models

# Create your models here.
class NewsLetterUsers(models.Model):
    """Email for subscribing confirmation"""
    email = models.EmailField(unique=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'NewsLetter Users'

    def __str__(self):
        return self.email

newsletters/forms.py
from django import forms
# Same App importing
from newsletters.models import NewsLetterUsers


class NewsLetterUsersSignUpForm(forms.ModelForm):
    """Form for input emails"""
    class Meta:
        model = NewsLetterUsers
        fields = ['email']

        def clean_email(self, email=None):
            """Cleaned email data"""
            email = self.clean_email(email)
            return email

newsletters/views.py
from django.conf import settings
from django.shortcuts import render
from django.contrib import messages
from django.template.loader import get_template
from django.core.mail import send_mail, EmailMultiAlternatives
# Same App importing
from newsletters.models import NewsLetterUsers
from newsletters.forms import NewsLetterUsersSignUpForm

# Create your views here.


def newsletter_subscribe(request):
    """Subscription"""
    form = NewsLetterUsersSignUpForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsLetterUsers.objects.filter(email=instance.email).exists():
            messages.warning(request, 'Email already exists!',
                             'alert alert-warning alert-dismissible')
        else:
            instance.save()
            messages.success(request, 'Email has been submitted!',
                             'alert alert-success alert-dismissible')
            subject = 'Thank you for joining my Newsletter!'
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]

            with open(settings.BASE_DIR + '/templates/newsletters/subscribe_email_message.txt') as f:
                signup_message = f.read()
            message = EmailMultiAlternatives(subject=subject, body=signup_message,
                                             from_email=from_email, to=to_email)
            html_template = get_template('/templates/newsletters/subscribe_email_message.html').render()
            message.attach_alternative(html_template, 'text/html')
            message.send()

            # Hard coding, But also works fine
            # signup_message = 'Welcome to my Portfolio! If you would like to unsubscribe visit, http://127.0.0.1:8000/newsletter/unsubscribe'
            # send_mail(subject=subject, from_email=from_email, recipient_list=to_email,
            #           message=signup_message, fail_silently=False)

    context = {
        'form': form,
    }
    template = 'newsletters/subscribe.html'
    return render(request, template, context)


def newsletter_unsubscribe(request):
    """Un-subscription"""
    form = NewsLetterUsersSignUpForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsLetterUsers.objects.filter(email=instance.email).exists():
            NewsLetterUsers.objects.filter(email=instance.email).delete()
            messages.success(request, 'Email has been removed!',
                             'alert alert-success alert-dismissible')
            subject = 'You have been Unsubscribed!'
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]

            with open(settings.BASE_DIR + '/newsletters/unsubscribe_email_message.txt') as f:
                signup_message = f.read()
            message = EmailMultiAlternatives(subject=subject, body=signup_message,
                                             from_email=from_email, to=to_email)
            html_template = get_template('newsletters/unsubscribe_email_message.html').render()
            message.attach_alternative(html_template, 'text/html')
            message.send()

            # Hard coding, But also works fine
            # signup_message = 'Sorry to see you go! Let us know if there is an issue with my service.'
            # send_mail(subject=subject, from_email=from_email, recipient_list=to_email,
            #           message=signup_message, fail_silently=False)

        else:
            messages.warning(request, 'Email is not in the Database!',
                             'alert alert-warning alert-dismissible')

    context = {
        'form': form,
    }
    template = 'newsletters/unsubscribe.html'
    return render(request, template, context)

templates/newsletters/subscribe.html
{% extends 'blog/base.html' %}
{% block title %} newsletter {% endblock %}

{% block content %}
<div class="popular-news-area section-padding-80-50" style="margin-top: -100px;">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-4">
                    <!-- Newsletter Widget -->
                    {% if messages %}
                        {% for message in messages %}
                            <div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% else %}
                    <div class="newsletter-widget">
                        <h4>Newsletter</h4>
                        <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                        <form action="{% url 'newsletters:subscribe' %}" method="POST">{% csrf_token %}
                            <input type="text" name="email" placeholder="Email">
                           <button type="submit" class="btn w-100">Subscribe</button>
                        </form>

                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
</div>


{% endblock %}

templates/newsletters/subscribe_email_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Subscription email</title>
</head>
<body>
    <h2>Welcome to my Newsletter!</h2>
    <h4>Thank you for joining.</h4>
    <h5>This is our dashboard, <a href="https://joy210.github.io/Shohoz_Tech/index.html">visit</a></h5>
    <p>To unsubscribe, <a href="{% url 'newsletters:unsubscribe'%}">click here</a></p>
</body>
</html>

templates/newsletters/unsubscribe.html
{% extends 'blog/base.html' %}
{% block title %} unsubscribe newsletter {% endblock %}

{% block content %}

<div class="popular-news-area section-padding-80-50" style="margin-top: -100px;">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-4">
                    <!-- Newsletter Widget -->
                    <div class="newsletter-widget">
                        {% if messages %}
                            {% for message in messages %}
                                <div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                         {% else %}
                        <h4> Unsubscribe Newsletter</h4>
                        <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                        <form action="{% url 'newsletters:unsubscribe' %}" method="POST">{% csrf_token %}
                            <input type="text" name="email" placeholder="Email">
                           <button type="submit" class="btn w-100">Unsubscribe</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
</div>


{% endblock %}

templates/newsletters/unsubscribe_email_message.html
{% extends 'news/blog.html' %}
{% block title %} newsletter {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>Sorry to see you go!</h2>
        <h4>Let us know if there is an issue with my service.</h4>
    </div>
</div>

{% endblock %}